"""
Django settings for idi project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

from django.core.exceptions import ImproperlyConfigured
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


def env_bool(name, default=False):
    """Parse a boolean env var.

    Accepts the forms people actually write. The previous implementation compared
    against the literal string 'true', so a .env carrying DEBUG='1' silently
    evaluated to False -- which switched local development into production mode
    (SSL redirect, secure-only cookies) and broke admin login over plain HTTP.
    """
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().strip('\'"').lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=()):
    """Comma-separated env var -> list of stripped, non-empty strings."""
    raw = os.getenv(name)
    if not raw:
        return list(default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# In DEBUG the insecure fallback keeps local setup frictionless; with DEBUG off a
# missing SECRET_KEY is fatal rather than silently booting on a key that is public
# in this repository's history.
SECRET_KEY = os.getenv('SECRET_KEY') or ''
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY must be set in the environment when DEBUG is off.'
        )

# Hosts that serve the real site. Overridable per-environment via ALLOWED_HOSTS.
ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    default=['idi.africa', 'www.idi.africa', '170.187.145.60'],
)

# Loopback is allowed in every environment, not just development. The container
# HEALTHCHECK and any orchestrator probe request http://127.0.0.1:8000/health/
# from inside the container, so excluding these makes the container report
# unhealthy in production. Allowing loopback names carries no real Host-header
# risk: an external attacker cannot cause a request to arrive with a loopback
# Host that resolves anywhere useful.
LOOPBACK_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Tunnelling hosts, by contrast, are a development convenience only: leaving them
# in production would let an attacker-controlled ngrok domain pass the check.
DEV_ONLY_HOSTS = [
    '.ngrok-free.app', '.ngrok.io', '.ngrok.app', '.ngrok-free.dev', '.ngrok.dev',
    '.localtunnel.me', '.loca.lt',
]
DEV_ONLY_ORIGINS = [
    'http://localhost', 'http://localhost:8000', 'http://127.0.0.1', 'http://127.0.0.1:8000',
    'https://*.ngrok-free.app', 'https://*.ngrok-free.dev', 'https://*.ngrok.io',
    'https://*.ngrok.app', 'https://*.ngrok.dev', 'https://*.localtunnel.me', 'https://*.loca.lt',
]
ALLOWED_HOSTS += [h for h in LOOPBACK_HOSTS if h not in ALLOWED_HOSTS]
if DEBUG:
    ALLOWED_HOSTS += DEV_ONLY_HOSTS

# Google Analytics 4 measurement id (e.g. 'G-XXXXXXXXXX'). Empty = analytics off.
GA_MEASUREMENT_ID = os.getenv('GA_MEASUREMENT_ID', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites",  # new
    "django.contrib.sitemaps",  # new 
    'storages',
    'ckeditor',
    'ckeditor_uploader',
    # internal apps
    'apps.home',
    'apps.credentials',
]

SITE_ID = 1  # new

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
]

# CSRF / session cookies.
# These are gated on DEBUG rather than hardcoded True: marking cookies Secure
# means the browser will not send them over plain HTTP, so an unconditional True
# makes admin login impossible on a local http://127.0.0.1 server.
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access the CSRF cookie
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Origins trusted to submit forms.
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    default=['https://idi.africa', 'https://www.idi.africa', 'http://170.187.145.60'],
)
if DEBUG:
    CSRF_TRUSTED_ORIGINS += DEV_ONLY_ORIGINS

ROOT_URLCONF = 'idi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.home.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'idi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Falling back to SQLite in production would silently start the site against an
    # empty local file instead of the real database. Fail loudly instead.
    raise ImproperlyConfigured(
        'DB_NAME must be set in the environment when DEBUG is off.'
    )



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# django-compressor was installed and enabled, but not one template contained a
# "compress" template tag, so it only ever produced stale artefacts in
# static/CACHE. WhiteNoise's CompressedManifestStaticFilesStorage already handles
# hashing plus gzip/brotli, so the dependency was removed entirely.
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Static files storage. Django 5.1+ removed STATICFILES_STORAGE in favour of STORAGES;
# this is what actually enables WhiteNoise manifest hashing + gzip/brotli compression.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Media storage on Garage (S3-compatible object storage) when USE_S3=True.
# Static files stay on WhiteNoise; only user-uploaded media goes to S3.
USE_S3 = os.getenv('USE_S3', 'False').lower() == 'true'
if USE_S3:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')          # e.g. https://garage.example.com
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'garage')
    AWS_S3_ADDRESSING_STYLE = 'path'        # Garage requires path-style, not virtual-host
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False           # keep distinct uploads with the same name
    AWS_QUERYSTRING_AUTH = False            # public media -> clean, unsigned URLs
    AWS_DEFAULT_ACL = None                  # Garage: manage access via bucket policy, not per-object ACLs
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN') or None  # optional CDN/custom media host
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        # No location prefix: object keys mirror the on-disk media layout (uploads/...),
        # so an existing local media tree syncs to the bucket root 1:1.
    }

# Private storage for archived certificate PDFs.
# A SEPARATE bucket, not a prefix: the Garage website flag is per-bucket and the
# Traefik /media/ router matches the whole prefix, so anything in the default
# bucket is world-readable with a one-year immutable cache. querystring_auth=True
# makes admin download links short-lived presigned URLs instead.
CERT_BUCKET_NAME = os.getenv('CERT_BUCKET_NAME', '')
if USE_S3 and CERT_BUCKET_NAME:
    STORAGES['certificates'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': CERT_BUCKET_NAME,
            'endpoint_url': os.getenv('AWS_S3_ENDPOINT_URL'),
            'region_name': os.getenv('AWS_S3_REGION_NAME', 'garage'),
            'addressing_style': 'path',
            'signature_version': 's3v4',
            'querystring_auth': True,     # presigned, expiring URLs
            'querystring_expire': 300,    # 5 minutes
            'file_overwrite': False,
            'default_acl': None,
        },
    }

# File upload settings - ensure proper permissions
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400   # 25MB

# CKEditor settings
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"


customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

CKEDITOR_CONFIGS = {
    'extends': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'extraPlugins': 'uploadimage',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
    }
}
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_ALLOW_NONIMAGE_FILES = False
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session Configuration - Database sessions
SESSION_COOKIE_AGE = 86400  # 24 hours

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
# SAMEORIGIN, not DENY: the CKEditor file browser used by the admin renders in a
# same-origin iframe, which DENY blocks. Defined exactly once -- it was previously
# set in two places with conflicting values.
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# HTTPS hardening — only enforced in production (DEBUG=False) so local HTTP dev still works.
# nginx terminates TLS and forwards X-Forwarded-Proto, so trust it for is_secure().
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # On by default, but overridable so the container can be run locally in
    # production mode (DEBUG=False) without TLS. Left unconditional, plain HTTP to
    # 127.0.0.1:8000 gets a 301 to https://127.0.0.1:8000, where gunicorn speaks
    # no TLS -- the browser then hangs on a handshake that never completes and the
    # site appears to load forever. In real deployments Traefik terminates TLS and
    # forwards X-Forwarded-Proto, so this stays on there.
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=True)
    # Health checks (Docker/orchestrators) probe over plain HTTP — exempt them
    # from the HTTPS redirect so they get 200 instead of a 301.
    SECURE_REDIRECT_EXEMPT = [r'^health/$']
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # Every executed SQL statement was previously logged in development,
        # which buries real output. Opt in explicitly with SQL_DEBUG=true.
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if env_bool('SQL_DEBUG') else 'WARNING',
            'propagate': False,
        },
        'apps.credentials': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ---------------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------------
# There was previously no CACHES setting at all, so Django fell back to a
# per-process LocMemCache. Gunicorn runs 4 preloaded workers that recycle at
# --max-requests, which makes any cache-based counter (rate limiting in
# apps.credentials, in particular) split four ways and reset unpredictably.
# Locally this points at the shared dev-valkey container; Valkey speaks the
# Redis protocol, so Django's built-in RedisCache works unchanged.
CACHE_URL = os.getenv('CACHE_URL', 'redis://127.0.0.1:6379/3')
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': CACHE_URL,
        # dev-valkey is shared with other projects: keep IDI keys in their own
        # namespace as well as their own database index.
        'KEY_PREFIX': os.getenv('CACHE_KEY_PREFIX', 'idi'),
    }
}

# ---------------------------------------------------------------------------
# Proxy / client IP
# ---------------------------------------------------------------------------
# Traefik terminates TLS and proxies to gunicorn, appending the real client to
# X-Forwarded-For. Number of proxy hops we control, counted from the right of
# that header. Anything further left is client-supplied and must not be trusted.
TRUSTED_PROXY_HOPS = int(os.getenv('TRUSTED_PROXY_HOPS', '1'))

# Salt for hashing visitor IPs in the certificate scan log. Deliberately NOT
# SECRET_KEY: rotating the secret key is routine and must neither break scan
# de-duplication nor de-anonymise the log. An unsalted SHA-256 of an IPv4 address
# is trivially reversible, so this salt is the entire privacy control -- keep it
# secret and do not remove it.
SCAN_IP_SALT = os.getenv('SCAN_IP_SALT', '')
if not SCAN_IP_SALT:
    if DEBUG:
        SCAN_IP_SALT = 'dev-only-scan-salt'
    else:
        raise ImproperlyConfigured(
            'SCAN_IP_SALT must be set in the environment when DEBUG is off.'
        )

# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------
# Previously absent entirely, which meant contact-form notifications could not be
# sent and BrokenLinkEmailsMiddleware silently mailed nobody. Locally this points
# at the dev-mailpit container (web UI on :8025).
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '127.0.0.1')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '1025'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', default=False)
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'IDI Africa <noreply@idi.africa>')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Where contact-form notifications go.
CONTACT_NOTIFICATION_EMAILS = env_list(
    'CONTACT_NOTIFICATION_EMAILS', default=['collectives@idi.africa']
)

_admin_emails = env_list('ADMIN_EMAILS')
ADMINS = [('IDI Admin', addr) for addr in _admin_emails]
MANAGERS = ADMINS
