# Generated by Django 6.1.1 on 2026-09-07 17:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'DIDA Executive Cohort 3'", max_length=120)),
                ('code', models.CharField(help_text="e.g. 'EXEC-2026-C3'", max_length=24, unique=True)),
                ('program_slug', models.CharField(blank=True, help_text='Slug of the related home.Program, if any. Plain text by design.', max_length=60)),
                ('program_title', models.CharField(max_length=200)),
                ('program_type_label', models.CharField(blank=True, help_text="e.g. 'Executive Program'", max_length=60)),
                ('credential_title', models.CharField(default='Certificate of Completion', max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('default_completion_date', models.DateField(blank=True, null=True)),
                ('default_issue_date', models.DateField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, help_text="e.g. '12 weeks'", max_length=100)),
                ('format', models.CharField(blank=True, help_text="e.g. 'Hybrid - Nairobi'", max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('signatory_1_name', models.CharField(blank=True, max_length=120)),
                ('signatory_1_title', models.CharField(blank=True, max_length=160)),
                ('signatory_2_name', models.CharField(blank=True, max_length=120)),
                ('signatory_2_title', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, help_text='Human-readable record number printed on the certificate.', max_length=32, unique=True)),
                ('token', models.CharField(db_index=True, help_text='Unguessable verification code. Canonical form: uppercase, no hyphens.', max_length=12, unique=True)),
                ('recipient_full_name', models.CharField(help_text='Exactly as printed.', max_length=160)),
                ('recipient_email', models.EmailField(blank=True, help_text='Internal only. Never shown publicly.', max_length=254)),
                ('recipient_country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2.', max_length=2)),
                ('program_slug', models.CharField(blank=True, max_length=60)),
                ('program_title', models.CharField(max_length=200)),
                ('program_type_label', models.CharField(blank=True, max_length=60)),
                ('credential_title', models.CharField(default='Certificate of Completion', max_length=200)),
                ('duration_text', models.CharField(blank=True, max_length=100)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('signatory_1_name', models.CharField(blank=True, max_length=120)),
                ('signatory_1_title', models.CharField(blank=True, max_length=160)),
                ('signatory_2_name', models.CharField(blank=True, max_length=120)),
                ('signatory_2_title', models.CharField(blank=True, max_length=160)),
                ('completion_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('expires_on', models.DateField(blank=True, help_text='Blank = never expires.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, help_text='Internal. Never shown publicly.')),
                ('revocation_public_note', models.CharField(blank=True, help_text='Shown on the public verification page.', max_length=200)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal. Never shown publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('first_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='credentials.certificate')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='credentials.cohort')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('superseded', 'Superseded'), ('edited', 'Edited'), ('pdf_replaced', 'PDF replaced')], max_length=24)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='credentials.certificate')),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SerialSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='DIDA-IDI', max_length=24)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serial sequence',
                'verbose_name_plural': 'Serial sequences',
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='uniq_serial_prefix_year')],
            },
        ),
        migrations.CreateModel(
            name='CertificateScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_serial', models.CharField(blank=True, max_length=32)),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('outcome', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('not_found', 'Not found'), ('malformed', 'Malformed code')], db_index=True, max_length=12)),
                ('lookup_method', models.CharField(choices=[('qr', 'QR / short link'), ('manual', 'Manual entry'), ('direct', 'Direct link')], default='direct', max_length=8)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('ua_family', models.CharField(blank=True, max_length=40)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('referer_host', models.CharField(blank=True, help_text='Host only; never a full URL.', max_length=120)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='credentials.certificate')),
            ],
            options={
                'verbose_name': 'Certificate scan',
                'verbose_name_plural': 'Certificate scans',
                'ordering': ['-scanned_at', '-id'],
                'indexes': [models.Index(fields=['certificate', 'scanned_at'], name='scan_cert_time_idx'), models.Index(fields=['outcome', 'scanned_at'], name='scan_outcome_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status', 'issue_date'], name='cert_status_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['cohort', 'status'], name='cert_cohort_status_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['recipient_full_name'], name='cert_recipient_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'revoked'), _negated=True), ('revoked_at__isnull', False), _connector='OR'), name='cert_revoked_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('expires_on__gte', models.F('issue_date')), _connector='OR'), name='cert_expiry_after_issue'),
        ),
    ]
