# Generated by Django 6.1.1 on 2026-09-07 17:59

import apps.credentials.storage
import apps.credentials.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, help_text='Archival copy. Admin only — never shown on the public page.', null=True, storage=apps.credentials.storage.certificate_storage, upload_to=apps.credentials.storage.certificate_pdf_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.credentials.validators.PdfMagicBytesValidator(), apps.credentials.validators.validate_pdf_size]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_sha256',
            field=models.CharField(blank=True, db_index=True, help_text='Fingerprint of the stored PDF. Lets staff compare a file someone emailed them against the archived original.', max_length=64),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
