# Generated by Django 5.1.4 on 2025-05-03 09:48

from django.db import migrations, models
from django.db import connection


def remove_rating_field_if_exists(apps, schema_editor):
    """Remove rating field only if it exists"""
    if connection.vendor != 'postgresql':
        return
    with connection.cursor() as cursor:
        # Check if the column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='home_testimonial' 
            AND column_name='rating'
        """)
        if cursor.fetchone():
            # Column exists, remove it
            cursor.execute("ALTER TABLE home_testimonial DROP COLUMN rating")


def reverse_remove_rating_field(apps, schema_editor):
    """Add rating field back"""
    if connection.vendor != 'postgresql':
        return
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE home_testimonial 
            ADD COLUMN rating INTEGER DEFAULT 5 
            CHECK (rating >= 1 AND rating <= 5)
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            remove_rating_field_if_exists,
            reverse_remove_rating_field
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(help_text='Main image shown in grid', upload_to='uploads/projects/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='background_shape',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/team/shapes/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='uploads/team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/testimonials/'),
        ),
    ]
