# Generated by Django 5.1.4 on 2025-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(help_text='Main image shown in grid', upload_to='uploads/projects/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='background_shape',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/team/shapes/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='uploads/team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/testimonials/'),
        ),
    ]
