# Generated by Django 5.2 on 2025-08-12 20:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_testimonial_rating_alter_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('program_type', models.CharField(choices=[('fellowship', 'Fellowship'), ('executive', 'Executive Program'), ('bootcamp', 'Bootcamp'), ('course', 'Course'), ('workshop', 'Workshop')], default='fellowship', max_length=20)),
                ('short_description', models.TextField(help_text='Brief description for card display')),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Full Description')),
                ('image', models.ImageField(help_text='Program card image', upload_to='uploads/programs/')),
                ('duration', models.CharField(blank=True, help_text="e.g., '12 weeks', '3 months'", max_length=100)),
                ('format', models.CharField(blank=True, help_text="e.g., 'Online', 'Hybrid', 'In-person'", max_length=100)),
                ('target_audience', models.TextField(blank=True, help_text='Who this program is for')),
                ('application_url', models.URLField(blank=True, help_text='Apply Now link')),
                ('learn_more_url', models.URLField(blank=True, help_text='Learn More link')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='uploads/programs/brochures/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured programs section')),
                ('application_open', models.BooleanField(default=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(default=2025)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
