# Generated by Django 5.2 on 2025-08-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='uploads/clients/')),
                ('website', models.URLField(blank=True, help_text="Client's website URL")),
                ('industry', models.CharField(choices=[('fintech', 'FinTech'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('agriculture', 'Agriculture'), ('logistics', 'Logistics'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('government', 'Government'), ('ngo', 'NGO/Non-Profit'), ('other', 'Other')], default='other', max_length=100)),
                ('project_description', models.TextField(blank=True, help_text='Brief description of the project/engagement')),
                ('collaboration_year', models.IntegerField(default=2025, help_text='Year of collaboration')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured clients section')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='uploads/partners/')),
                ('website', models.URLField(blank=True, help_text="Partner's website URL")),
                ('description', models.TextField(blank=True, help_text='Brief description of the partnership')),
                ('partnership_type', models.CharField(choices=[('strategic', 'Strategic Partner'), ('technology', 'Technology Partner'), ('funding', 'Funding Partner'), ('academic', 'Academic Partner'), ('implementation', 'Implementation Partner'), ('media', 'Media Partner')], default='strategic', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured partners section')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'name'],
            },
        ),
    ]
