# Generated by Django 6.0.5 on 2026-05-22 08:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_client_partner'),
    ]

    operations = [
        # Program and testimonial.rating already exist in the DB from RunSQL in
        # migrations 0002/0003 (which never registered Django state). Reconcile
        # state only — no DB changes — so these stop being regenerated.
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('program_type', models.CharField(choices=[('fellowship', 'Fellowship'), ('executive', 'Executive Program'), ('bootcamp', 'Bootcamp'), ('course', 'Course'), ('workshop', 'Workshop')], default='fellowship', max_length=20)),
                ('short_description', models.TextField(help_text='Brief description for card display')),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Full Description')),
                ('image', models.ImageField(help_text='Program card image', upload_to='uploads/programs/')),
                ('duration', models.CharField(blank=True, help_text="e.g., '12 weeks', '3 months'", max_length=100)),
                ('format', models.CharField(blank=True, help_text="e.g., 'Online', 'Hybrid', 'In-person'", max_length=100)),
                ('target_audience', models.TextField(blank=True, help_text='Who this program is for')),
                ('application_url', models.URLField(blank=True, help_text='Apply Now link')),
                ('learn_more_url', models.URLField(blank=True, help_text='Learn More link')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='uploads/programs/brochures/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured programs section')),
                ('application_open', models.BooleanField(default=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(default=2025)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        ]),
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.CharField(blank=True, help_text='One-line challenge summary shown on the card', max_length=240),
        ),
        migrations.AddField(
            model_name='project',
            name='headline_stat',
            field=models.CharField(blank=True, help_text="Highlighted outcome stat, e.g. '40% reduction in service delivery time'", max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in the homepage hero card row'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated topic tags shown as pills, e.g. 'Governance, AI'", max_length=120),
        ),
    ]
