# Generated by Django 6.0.5 on 2026-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_program_remove_testimonial_rating_project_challenge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g. '120+', '14', '35+'", max_length=16)),
                ('label', models.CharField(help_text="e.g. 'Projects Delivered'", max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Stat',
                'verbose_name_plural': 'Home Stats',
                'ordering': ['order', 'id'],
            },
        ),
    ]
