# Generated by Django 6.0.5 on 2026-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Insights & Data'", max_length=80)),
                ('slug', models.SlugField(blank=True, help_text='Drives the illustration filename: services/{slug}.webp', unique=True)),
                ('description', models.CharField(max_length=200)),
                ('type_label', models.CharField(blank=True, help_text="e.g. 'Diagnostic'", max_length=40)),
                ('output_label', models.CharField(blank=True, help_text="e.g. 'Synthesis'", max_length=40)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Pillar',
                'verbose_name_plural': 'Service Pillars',
                'ordering': ['order', 'id'],
            },
        ),
    ]
