# Generated by Django 6.1.1 on 2026-09-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_servicepillar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry_type', models.CharField(choices=[('strategic-partnership', 'Strategic Partnership'), ('academy-fellowship', 'DID Academy / Fellowship'), ('research-data', 'Insights & Data Collaborations'), ('careers', 'Career Opportunities'), ('general', 'General Inquiry')], default='general', max_length=32)),
                ('message', models.TextField()),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once someone has replied.')),
                ('handled_note', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_handled', '-created_at'], name='contact_handled_idx')],
            },
        ),
    ]
