# Generated by Django 6.1.1 on 2026-09-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first. Equal numbers sort alphabetically.'),
        ),
    ]
