# Generated by Django 6.1.1 on 2026-09-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_teammember_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short line under the title on the detail page.', max_length=250)),
                ('teaser', models.TextField(blank=True, help_text='Short description for the listing card. 1-2 sentences.')),
                ('category', models.CharField(blank=True, help_text="Shown as the card label, e.g. 'GENDER RIGHTS'.", max_length=80)),
                ('sector', models.CharField(blank=True, max_length=80)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('partners_text', models.CharField(blank=True, help_text="Partner names for the card, e.g. 'UNEP · GIZ · Action Lab'.", max_length=250)),
                ('timeline', models.CharField(blank=True, help_text="e.g. '2023 - 2024'", max_length=100)),
                ('challenge', models.CharField(blank=True, help_text='One-line problem summary shown on the card.', max_length=300)),
                ('overview', models.TextField(blank=True)),
                ('our_role', models.TextField(blank=True)),
                ('key_insight', models.TextField(blank=True)),
                ('approach_text', models.TextField(blank=True)),
                ('outcome_text', models.TextField(blank=True)),
                ('measuring_success', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='uploads/case_studies/')),
                ('hero_image_static', models.CharField(blank=True, help_text='Path under static/ for legacy imported imagery. Ignored if an image is uploaded.', max_length=200)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Health, Digitisation, Youth'", max_length=200)),
                ('bg_color', models.CharField(blank=True, help_text="Tailwind class for the card background, e.g. 'bg-[#f5f1ea]'", max_length=40)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting it.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case study',
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g. '91%', '5', '<15 min'", max_length=40)),
                ('label', models.CharField(help_text="e.g. 'faster case research'", max_length=160)),
                ('kind', models.CharField(choices=[('outcome', 'Outcome (something we achieved)'), ('context', 'Context (describes the problem, not our result)')], default='outcome', max_length=10)),
                ('note', models.CharField(blank=True, help_text='Optional qualifier shown with the figure, e.g. the source or scope.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='home.casestudy')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order', 'id'],
            },
        ),
    ]
